name: Update Telegram Sticker

on:
  schedule:
    # Каждые четыре часа
    - cron: "0 */4 * * *"
  workflow_dispatch: {}

jobs:
  update-sticker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          STICKER_SET_NAME: ${{ secrets.STICKER_SET_NAME }}
          STICKER_SET_TITLE: ${{ secrets.STICKER_SET_TITLE }}
          # При желании можешь переопределить URL базовой картинки:
          # BASE_IMAGE_URL: ${{ secrets.BASE_IMAGE_URL }}
        run: |
          python main.py
